import { Database } from "lucide-react";

/**
 * Source Registry section. No source-registry artifact exists yet (the SPEC
 * model is reference-only), so this renders a clean empty state describing what
 * it will track. When a sources artifact is generated by the build pipeline,
 * wire it in here.
 */
export function SourceRegistryView() {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-12 text-center shadow-sm">
      <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-blue-50 text-blue-500">
        <Database className="h-6 w-6" />
      </div>
      <h2 className="text-base font-semibold text-slate-800">No sources registered yet</h2>
      <p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">
        The Source Registry will track public surplus data sources by state, county, access level,
        data format, and scrape rules.
      </p>
      <span className="mt-4 inline-flex items-center rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-500 ring-1 ring-inset ring-slate-500/20">
        Empty — no source data in this build
      </span>
    </div>
  );
}
